const teamsbrazilian2022 = [
  {
    id: 1,
    time: 'América Futebol Clube',
    ano_de_fundação: 1912,
    escudo: './assets/escudos/america.png',
    mascote: 'Coelho',
    localização: 'Belo Horizonte',
    titulos_campeonato_brasileiro: 0,
    titulos_libertadores: 0,
  },
  {
    id: 2,
    time: 'Club Athletico Paranaense',
    ano_de_fundação: 1924,
    escudo: './assets/escudos/athletico.png',
    mascote: 'Furacão',
    localização: 'Curitiba',
    titulos_campeonato_brasileiro: 1,
    titulos_libertadores: 0,
  },
  {
    id: 3,
    time: 'Atlético Clube Goianiense',
    ano_de_fundação: 1937,
    escudo: './assets/escudos/atletico-go.png',
    mascote: 'Dragão',
    localização: 'Goiânia',
    titulos_campeonato_brasileiro: 0,
    titulos_libertadores: 0,
  },
  {
    id: 4,
    time: 'Clube Atlético Mineiro',
    ano_de_fundação: 1908,
    escudo: './assets/escudos/atletico-mg.png',
    mascote: 'Galo',
    localização: 'Belo Horizonte',
    titulos_campeonato_brasileiro: 2,
    titulos_libertadores: 1,
  },
  {
    id: 5,
    time: 'Avaí Futebol Clube',
    ano_de_fundação: 1923,
    escudo: './assets/escudos/avai.png',
    mascote: 'Leão',
    localização: 'Florianópolis',
    titulos_campeonato_brasileiro: 0,
    titulos_libertadores: 0,
  },
  {
    id: 6,
    time: 'Botafogo de Futebol e Regatas',
    ano_de_fundação: 1904,
    escudo: './assets/escudos/botafogo.png',
    mascote: 'Biriba',
    localização: 'Rio de Janeiro',
    titulos_campeonato_brasileiro: 2,
    titulos_libertadores: 0,
  },
  {
    id: 7,
    time: 'Red Bull Bragantino',
    ano_de_fundação: 1928,
    escudo: './assets/escudos/bragantino.png',
    mascote: 'Leão',
    localização: 'Bragança Paulista',
    titulos_campeonato_brasileiro: 0,
    titulos_libertadores: 0,
  },
  {
    id: 8,
    time: 'Ceará Sporting Club',
    ano_de_fundação: 1914,
    escudo: './assets/escudos/ceara.png',
    mascote: 'Vovô',
    localização: 'Fortaleza',
    titulos_campeonato_brasileiro: 0,
    titulos_libertadores: 0,
  },
  {
    id: 9,
    time: 'Sport Club Corinthians Paulista',
    ano_de_fundação: 1910,
    escudo: './assets/escudos/corinthians.png',
    mascote: 'Mosqueteiro',
    localização: 'São Paulo',
    titulos_campeonato_brasileiro: 7,
    titulos_libertadores: 1,
  },
  {
    id: 10,
    time: 'Coritiba Foot Ball Club',
    ano_de_fundação: 1909,
    escudo: './assets/escudos/coritiba.png',
    mascote: 'Vovô Coxa',
    localização: 'Curitiba',
    titulos_campeonato_brasileiro: 1,
    titulos_libertadores: 0,
  },
  {
    id: 11,
    time: 'Cuiabá Esporte Clube',
    ano_de_fundação: 2001,
    escudo: './assets/escudos/cuiaba.png',
    mascote: 'Peixe Dourado',
    localização: 'Cuiabá',
    titulos_campeonato_brasileiro: 0,
    titulos_libertadores: 0,
  },
  {
    id: 12,
    time: 'Clube de Regatas do Flamengo',
    ano_de_fundação: 1895,
    escudo: './assets/escudos/flamengo.png',
    mascote: 'Urubu',
    localização: 'Rio de Janeiro',
    titulos_campeonato_brasileiro: 8,
    titulos_libertadores: 2,
  },
  {
    id: 13,
    time: 'Fluminense Football Club',
    ano_de_fundação: 1902,
    escudo: './assets/escudos/fluminense.png',
    mascote: 'Guerreirinho',
    localização: 'Rio de Janeiro',
    titulos_campeonato_brasileiro: 4,
    titulos_libertadores: 0,
  },
  {
    id: 14,
    time: 'Fortaleza Esporte Clube',
    ano_de_fundação: 1918,
    escudo: './assets/escudos/fortaleza.png',
    mascote: 'Leão',
    localização: 'Fortaleza',
    titulos_campeonato_brasileiro: 0,
    titulos_libertadores: 0,
  },
  {
    id: 15,
    time: 'Goiás Esporte Clube',
    ano_de_fundação: 1943,
    escudo: './assets/escudos/goias.png',
    mascote: 'Periquito',
    localização: 'Goiânia',
    titulos_campeonato_brasileiro: 0,
    titulos_libertadores: 0,
  },
  {
    id: 16,
    time: 'Sport Club Internacional',
    ano_de_fundação: 1909,
    escudo: './assets/escudos/internacional.png',
    mascote: 'Saci',
    localização: 'Porto Alegre',
    titulos_campeonato_brasileiro: 3,
    titulos_libertadores: 2,
  },
  {
    id: 17,
    time: 'Esporte Clube Juventude',
    ano_de_fundação: 1913,
    escudo: './assets/escudos/juventude.png',
    mascote: 'Periquito',
    localização: 'Caxias do Sul',
    titulos_campeonato_brasileiro: 0,
    titulos_libertadores: 0,
  },
  {
    id: 18,
    time: 'Sociedade Esportiva Palmeiras',
    ano_de_fundação: 1914,
    escudo: './assets/escudos/palmeiras.png',
    mascote: 'Porco',
    localização: 'São Paulo',
    titulos_campeonato_brasileiro: 10,
    titulos_libertadores: 3,
  },
  {
    id: 19,
    time: 'Santos Futebol Clube',
    ano_de_fundação: 1912,
    escudo: './assets/escudos/santos.png',
    mascote: 'Baleia',
    localização: 'Santos',
    titulos_campeonato_brasileiro: 8,
    titulos_libertadores: 3,
  },
  {
    id: 20,
    time: 'São Paulo Futebol Clube',
    ano_de_fundação: 1930,
    escudo: './assets/escudos/saopaulo.png',
    mascote: 'Santo Paulo',
    localização: 'São Paulo',
    titulos_campeonato_brasileiro: 6,
    titulos_libertadores: 3,
  },
];

const findALLteamsbrazilian2022service = () => {
  return teamsbrazilian2022;
};

const findByIdteambrazilian2022service = (idParam) => {
    return teamsbrazilian2022.find((teamsbrazilian2022) => teamsbrazilian2022.id === idParam);
};

module.exports ={
    findALLteamsbrazilian2022service,
    findByIdteambrazilian2022service,
};